language: rust

addons:
  apt:
    packages: binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev make
before_install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            wget https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.xz
            tar -xvf nasm-2.14.02.tar.xz
            cd nasm-2.14.02
            ./configure
            make
            sudo make install
            cd ..
            nasm --version
        fi

matrix:
  allow_failures:
  - rust: nightly

jobs:
  include:
      - name: "Linux build"
        rust: nightly-2019-02-21
        script: make examples && ./simple_encoding
      - name: "macOS build"
        os: osx
        rust: nightly-2019-02-21
        script: make examples && ./simple_encoding
      - name: "Linux build (Rust nightly)"
        rust: nightly
        script: make examples && ./simple_encoding
